<template>
  <div class="new-product-entry">
    <!-- Header -->
    <div class="entry-header">
      <button class="back-btn" @click="$emit('close')">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="15 18 9 12 15 6"/></svg>
        {{ t('newProduct.back') }}
      </button>
      <h2 class="entry-title">{{ t('newProduct.title') }}</h2>
    </div>

    <!-- Stepper -->
    <div class="stepper">
      <div v-for="(step, idx) in stepsLabels" :key="idx" class="step" :class="{ active: currentStep === idx, done: currentStep > idx }">
        <div class="step-circle">
          <svg v-if="currentStep > idx" xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"><polyline points="20 6 9 17 4 12"/></svg>
          <span v-else>{{ idx + 1 }}</span>
        </div>
        <span class="step-label">{{ step }}</span>
        <div v-if="idx < stepsLabels.length - 1" class="step-line" :class="{ filled: currentStep > idx }"></div>
      </div>
    </div>

    <!-- Step 1: Select Fields -->
    <transition name="slide-fade" mode="out-in">
      <div v-if="currentStep === 0" key="step0" class="step-content">
        <div class="step-desc">
          <h3>{{ t('newProduct.selectFieldsTitle') }}</h3>
          <p>{{ t('newProduct.selectFieldsDesc') }}</p>
        </div>
        <div class="field-categories">
          <div v-for="cat in fieldCategories" :key="cat.name" class="field-category">
            <h4 class="cat-title">{{ cat.name }}</h4>
            <div class="field-chips">
              <label
                v-for="field in cat.fields"
                :key="field.key"
                class="field-chip"
                :class="{ selected: selectedFields.includes(field.key), required: field.required, disabled: field.required || field.autoGenerate }"
              >
                <input
                  type="checkbox"
                  :checked="selectedFields.includes(field.key)"
                  :disabled="field.required || field.autoGenerate"
                  @change="toggleField(field.key)"
                />
                <span class="chip-text">{{ field.label }}</span>
                <span v-if="field.required" class="chip-badge">{{ t('newProduct.required') }}</span>
                <span v-if="field.autoGenerate" class="chip-badge chip-auto">Auto</span>
              </label>
            </div>
          </div>
        </div>
        <div class="step-actions">
          <button class="btn-primary" @click="goToStep(1)" :disabled="selectedFields.length === 0">
            {{ t('newProduct.nextFillData') }}
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="9 18 15 12 9 6"/></svg>
          </button>
        </div>
      </div>
    </transition>

    <!-- Step 2: Fill Data Table -->
    <transition name="slide-fade" mode="out-in">
      <div v-if="currentStep === 1" key="step1" class="step-content">
        <div class="step-desc">
          <h3>{{ t('newProduct.fillDataTitle') }}</h3>
          <p>{{ t('newProduct.fillDataDesc') }}</p>
        </div>
        <!-- Add Column Button -->
        <div class="table-toolbar">
          <button class="btn-outline btn-sm" @click="showAddColumnDialog = true">
            <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></svg>
            {{ t('newProduct.addColumn') }}
          </button>
          <button class="btn-outline btn-sm" @click="addRow">
            <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></svg>
            {{ t('newProduct.addRow') }}
          </button>
          <span class="row-count">{{ rows.length }} {{ t('newProduct.rowCount') }}</span>
        </div>
        <!-- Data Table -->
        <div class="table-wrapper">
          <table class="data-table">
            <thead>
              <tr>
                <th class="row-num">#</th>
                <th v-for="col in activeColumns" :key="col.key" class="col-header">
                  <span>{{ col.label }}</span>
                  <span v-if="col.autoGenerate" class="handle-hint">{{ t('newProduct.handleAutoGenerated') }}</span>
                  <button v-if="!col.required && !col.autoGenerate" class="col-remove" @click="removeColumn(col.key)" title="×">×</button>
                </th>
                <th class="row-actions">{{ locale === 'zh' ? '操作' : 'Actions' }}</th>
              </tr>
            </thead>
            <transition-group name="row-fade" tag="tbody">
              <tr v-for="(row, rIdx) in rows" :key="row._id">
                <td class="row-num">{{ rIdx + 1 }}</td>
                <td v-for="col in activeColumns" :key="col.key" class="cell" :class="{ 'cell-error': row._errors && row._errors[col.key] }">
                  <!-- Handle is auto-generated from Title, shown as readonly -->
                  <input
                    v-if="col.autoGenerate"
                    :value="generateHandle(row['Title'])"
                    class="cell-input cell-readonly"
                    readonly
                    :placeholder="t('newProduct.handleAutoGenerated')"
                  />
                  <select v-else-if="col.type === 'select'" v-model="row[col.key]" class="cell-input">
                    <option value="">-- --</option>
                    <option v-for="opt in col.options" :key="opt" :value="opt">{{ opt }}</option>
                  </select>
                  <textarea v-else-if="col.type === 'textarea'" v-model="row[col.key]" class="cell-input cell-textarea" rows="2"></textarea>
                  <input v-else v-model="row[col.key]" class="cell-input" :placeholder="col.placeholder || ''" :type="col.type === 'number' ? 'number' : 'text'" />
                  <span v-if="row._errors && row._errors[col.key]" class="cell-error-tip">{{ row._errors[col.key] }}</span>
                </td>
                <td class="row-actions">
                  <button class="btn-icon btn-danger" @click="removeRow(rIdx)" :title="t('newProduct.deleteRow')">
                    <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg>
                  </button>
                  <button class="btn-icon" @click="duplicateRow(rIdx)" :title="t('newProduct.duplicateRow')">
                    <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg>
                  </button>
                </td>
              </tr>
            </transition-group>
          </table>
        </div>
        <div class="step-actions">
          <button class="btn-secondary" @click="goToStep(0)">{{ t('newProduct.prevStep') }}</button>
          <button class="btn-primary" @click="goToStep(2)" :disabled="rows.length === 0">
            {{ t('newProduct.nextValidate') }}
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="9 18 15 12 9 6"/></svg>
          </button>
        </div>
      </div>
    </transition>

    <!-- Step 3: Validate -->
    <transition name="slide-fade" mode="out-in">
      <div v-if="currentStep === 2" key="step2" class="step-content">
        <div class="step-desc">
          <h3>{{ t('newProduct.validateTitle') }}</h3>
          <p>{{ t('newProduct.validateDesc') }}</p>
        </div>
        <div v-if="validating" class="validate-loading">
          <div class="spinner"></div>
          <span>{{ t('newProduct.validating') }}</span>
        </div>
        <div v-else-if="validationResult" class="validate-result">
          <div v-if="validationResult.valid" class="validate-success">
            <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="#10b981" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/><polyline points="22 4 12 14.01 9 11.01"/></svg>
            <h4>{{ t('newProduct.validationPassed') }}</h4>
            <p>{{ validationResult.message }}</p>
            <div class="validate-summary">
              <span><strong>{{ productCount }}</strong> {{ t('newProduct.products') }}</span>
              <span><strong>{{ rows.length }}</strong> {{ t('newProduct.variants') }}</span>
            </div>
          </div>
          <div v-else class="validate-errors">
            <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="#ef4444" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><line x1="15" y1="9" x2="9" y2="15"/><line x1="9" y1="9" x2="15" y2="15"/></svg>
            <h4>{{ t('newProduct.validationFailed') }}</h4>
            <p>{{ validationResult.errors.length }} {{ t('newProduct.errors') }}</p>
            <ul class="error-list">
              <li v-for="(err, i) in validationResult.errors" :key="i">
                <strong>Row {{ err.row }}</strong> — {{ err.field }}: {{ err.message }}
              </li>
            </ul>
          </div>
        </div>
        <div class="step-actions">
          <button class="btn-secondary" @click="goToStep(1)">{{ t('newProduct.backToEdit') }}</button>
          <button class="btn-primary" @click="goToStep(3)" :disabled="!validationResult || !validationResult.valid">
            {{ t('newProduct.nextExport') }}
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="9 18 15 12 9 6"/></svg>
          </button>
        </div>
      </div>
    </transition>

    <!-- Step 4: Export / Upload -->
    <transition name="slide-fade" mode="out-in">
      <div v-if="currentStep === 3" key="step3" class="step-content">
        <div class="step-desc">
          <h3>{{ t('newProduct.exportTitle') }}</h3>
          <p>{{ t('newProduct.exportDesc') }}</p>
        </div>
        <div class="export-options">
          <div class="export-card" @click="exportCSV">
            <div class="export-icon">
              <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="#6366f1" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>
            </div>
            <h4>{{ t('newProduct.exportCSV') }}</h4>
            <p>{{ t('newProduct.exportCSVDesc') }}</p>
          </div>
          <div class="export-card" :class="{ uploading }" @click="uploadToShopify">
            <div class="export-icon">
              <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="#10b981" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="17 8 12 3 7 8"/><line x1="12" y1="3" x2="12" y2="15"/></svg>
            </div>
            <h4>{{ uploading ? t('newProduct.uploading') : t('newProduct.addToShopify') }}</h4>
            <p>{{ t('newProduct.addToShopifyDesc') }}</p>
            <div v-if="uploading" class="upload-progress">
              <div class="progress-bar"><div class="progress-fill" :style="{ width: uploadProgress + '%' }"></div></div>
              <span>{{ uploadProgress }}%</span>
            </div>
          </div>
        </div>
        <!-- Upload Result -->
        <div v-if="uploadResult" class="upload-result">
          <div class="result-summary" :class="uploadResult.summary.failed > 0 ? 'partial' : 'success'">
            <span>{{ t('newProduct.uploadSuccess') }}: <strong>{{ uploadResult.summary.created }}</strong></span>
            <span v-if="uploadResult.summary.failed > 0">{{ t('newProduct.uploadFailed') }}: <strong>{{ uploadResult.summary.failed }}</strong></span>
          </div>
          <div v-for="(r, i) in uploadResult.data" :key="i" class="result-item" :class="r.status">
            <span class="result-title">{{ r.title }}</span>
            <span class="result-status">{{ r.status === 'created' ? '✓' : '✗ ' + r.message }}</span>
          </div>
        </div>
        <div class="step-actions">
          <button class="btn-secondary" @click="goToStep(2)">{{ t('newProduct.prevStep') }}</button>
          <button class="btn-primary" @click="$emit('close')">{{ t('newProduct.finish') }}</button>
        </div>
      </div>
    </transition>

    <!-- Add Column Dialog -->
    <transition name="fade">
      <div v-if="showAddColumnDialog" class="dialog-overlay" @click.self="showAddColumnDialog = false">
        <div class="dialog-box">
          <h3>{{ t('newProduct.addColumnTitle') }}</h3>
          <p>{{ t('newProduct.addColumnDesc') }}</p>
          <div class="dialog-fields">
            <label
              v-for="field in availableFieldsToAdd"
              :key="field.key"
              class="dialog-field-item"
              @click="addColumn(field.key)"
            >
              <span>{{ field.label }}</span>
              <span class="field-cat-tag">{{ field.category }}</span>
            </label>
          </div>
          <div class="dialog-actions">
            <button class="btn-secondary" @click="showAddColumnDialog = false">×</button>
          </div>
        </div>
      </div>
    </transition>
  </div>
</template>

<script setup>
import { ref, computed } from 'vue'
import { useI18n } from 'vue-i18n'
import axios from 'axios'

const { t, locale } = useI18n()
const emit = defineEmits(['close'])

const api = axios.create({ baseURL: '/api', withCredentials: true })

// ─── Handle generation: Title → lowercase, spaces/special → hyphens ───
function generateHandle(title) {
  if (!title) return ''
  return title
    .toLowerCase()
    .replace(/[^a-z0-9\u4e00-\u9fff]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .replace(/-{2,}/g, '-')
}

// ─── All available fields based on Shopify CSV format ───
const allFields = [
  // Product level
  { key: 'Handle', label: 'Handle', category: '基本信息 / Basic', required: false, autoGenerate: true, type: 'text', placeholder: 'auto-generated' },
  { key: 'Title', label: 'Title', category: '基本信息 / Basic', required: true, type: 'text', placeholder: 'Product title' },
  { key: 'Body (HTML)', label: 'Body (HTML)', category: '基本信息 / Basic', required: false, type: 'textarea', placeholder: 'Description (HTML)' },
  { key: 'Vendor', label: 'Vendor', category: '基本信息 / Basic', required: false, type: 'text', placeholder: 'Vendor' },
  { key: 'Product Category', label: 'Product Category', category: '基本信息 / Basic', required: false, type: 'text', placeholder: 'Category' },
  { key: 'Type', label: 'Type', category: '基本信息 / Basic', required: false, type: 'text', placeholder: 'Product type' },
  { key: 'Tags', label: 'Tags', category: '基本信息 / Basic', required: false, type: 'text', placeholder: 'tag1, tag2, ...' },
  { key: 'Published', label: 'Published', category: '基本信息 / Basic', required: false, type: 'select', options: ['true', 'false'] },
  { key: 'Status', label: 'Status', category: '基本信息 / Basic', required: false, type: 'select', options: ['active', 'draft', 'archived'] },
  // Options
  { key: 'Option1 Name', label: 'Option1 Name', category: '选项 / Options', required: false, type: 'text', placeholder: 'Size' },
  { key: 'Option1 Value', label: 'Option1 Value', category: '选项 / Options', required: false, type: 'text', placeholder: 'S / M / L' },
  { key: 'Option2 Name', label: 'Option2 Name', category: '选项 / Options', required: false, type: 'text', placeholder: 'Color' },
  { key: 'Option2 Value', label: 'Option2 Value', category: '选项 / Options', required: false, type: 'text', placeholder: 'Red / Blue' },
  { key: 'Option3 Name', label: 'Option3 Name', category: '选项 / Options', required: false, type: 'text', placeholder: 'Material' },
  { key: 'Option3 Value', label: 'Option3 Value', category: '选项 / Options', required: false, type: 'text', placeholder: 'Cotton' },
  // Variant
  { key: 'Variant SKU', label: 'Variant SKU', category: '变体 / Variant', required: true, type: 'text', placeholder: 'SKU' },
  { key: 'Variant Grams', label: 'Variant Grams', category: '变体 / Variant', required: false, type: 'number', placeholder: 'Weight (g)' },
  { key: 'Variant Inventory Tracker', label: 'Variant Inventory Tracker', category: '变体 / Variant', required: false, type: 'select', options: ['shopify', ''] },
  { key: 'Variant Inventory Qty', label: 'Variant Inventory Qty', category: '变体 / Variant', required: false, type: 'number', placeholder: 'Qty' },
  { key: 'Variant Inventory Policy', label: 'Variant Inventory Policy', category: '变体 / Variant', required: false, type: 'select', options: ['deny', 'continue'] },
  { key: 'Variant Fulfillment Service', label: 'Variant Fulfillment Service', category: '变体 / Variant', required: false, type: 'select', options: ['manual'] },
  { key: 'Variant Price', label: 'Variant Price', category: '变体 / Variant', required: true, type: 'number', placeholder: 'Price' },
  { key: 'Variant Compare At Price', label: 'Variant Compare At Price', category: '变体 / Variant', required: false, type: 'number', placeholder: 'Compare price' },
  { key: 'Variant Requires Shipping', label: 'Variant Requires Shipping', category: '变体 / Variant', required: false, type: 'select', options: ['true', 'false'] },
  { key: 'Variant Taxable', label: 'Variant Taxable', category: '变体 / Variant', required: false, type: 'select', options: ['true', 'false'] },
  { key: 'Variant Barcode', label: 'Variant Barcode', category: '变体 / Variant', required: false, type: 'text', placeholder: 'GTIN/EAN/UPC' },
  { key: 'Variant Weight Unit', label: 'Variant Weight Unit', category: '变体 / Variant', required: false, type: 'select', options: ['g', 'kg', 'lb', 'oz'] },
  { key: 'Cost per item', label: 'Cost per item', category: '变体 / Variant', required: false, type: 'number', placeholder: 'Cost' },
  // Image
  { key: 'Image Src', label: 'Image Src', category: '图片 / Image', required: false, type: 'text', placeholder: 'https://...' },
  { key: 'Image Position', label: 'Image Position', category: '图片 / Image', required: false, type: 'number', placeholder: '1' },
  { key: 'Image Alt Text', label: 'Image Alt Text', category: '图片 / Image', required: false, type: 'text', placeholder: 'Alt text' },
  // SEO
  { key: 'SEO Title', label: 'SEO Title', category: 'SEO', required: false, type: 'text', placeholder: 'SEO Title' },
  { key: 'SEO Description', label: 'SEO Description', category: 'SEO', required: false, type: 'textarea', placeholder: 'SEO Description' },
  // Metafields
  { key: 'Wholesale AUD (excl GST) (product.metafields.custom.retail_aud)', label: 'Wholesale AUD', category: 'Metafields', required: false, type: 'number', placeholder: 'AUD' },
  { key: 'Retail EUR (product.metafields.custom.retail_eur)', label: 'Retail EUR', category: 'Metafields', required: false, type: 'number', placeholder: 'EUR' },
  { key: 'Retail GBP (product.metafields.custom.retail_gbp)', label: 'Retail GBP', category: 'Metafields', required: false, type: 'number', placeholder: 'GBP' },
  { key: 'Retail NZD (product.metafields.custom.retail_nzd)', label: 'Retail NZD', category: 'Metafields', required: false, type: 'number', placeholder: 'NZD' },
  { key: 'Retail SGD (product.metafields.custom.retail_sgd)', label: 'Retail SGD', category: 'Metafields', required: false, type: 'number', placeholder: 'SGD' },
  { key: 'Retail USD (product.metafields.custom.retail_usd)', label: 'Retail USD', category: 'Metafields', required: false, type: 'number', placeholder: 'USD' },
  // Markets
  { key: 'Included / Australia', label: 'Included / Australia', category: '市场 / Market', required: false, type: 'select', options: ['true', 'false'] },
  { key: 'Price / Australia', label: 'Price / Australia', category: '市场 / Market', required: false, type: 'number', placeholder: '' },
  { key: 'Compare At Price / Australia', label: 'Compare At Price / Australia', category: '市场 / Market', required: false, type: 'number', placeholder: '' },
]

// ─── Steps ───
const stepsLabels = computed(() => [
  t('newProduct.stepSelectFields'),
  t('newProduct.stepFillData'),
  t('newProduct.stepValidate'),
  t('newProduct.stepExport')
])
const currentStep = ref(0)

// ─── Step 1: Field Selection ───
// Handle is always included (auto-generated), plus required fields
const selectedFields = ref(['Handle', ...allFields.filter(f => f.required).map(f => f.key)])

const fieldCategories = computed(() => {
  const cats = {}
  allFields.forEach(f => {
    if (!cats[f.category]) cats[f.category] = { name: f.category, fields: [] }
    cats[f.category].fields.push(f)
  })
  return Object.values(cats)
})

function toggleField(key) {
  const field = allFields.find(f => f.key === key)
  if (field && (field.required || field.autoGenerate)) return
  const idx = selectedFields.value.indexOf(key)
  if (idx >= 0) selectedFields.value.splice(idx, 1)
  else selectedFields.value.push(key)
}

// ─── Step 2: Data Table ───
const rows = ref([])
const showAddColumnDialog = ref(false)
let rowIdCounter = 0

const activeColumns = computed(() => {
  return selectedFields.value.map(key => allFields.find(f => f.key === key)).filter(Boolean)
})

const availableFieldsToAdd = computed(() => {
  return allFields.filter(f => !selectedFields.value.includes(f.key))
})

function createEmptyRow() {
  const row = { _id: ++rowIdCounter, _errors: null }
  selectedFields.value.forEach(key => { row[key] = '' })
  return row
}

function addRow() {
  rows.value.push(createEmptyRow())
}

function removeRow(idx) {
  rows.value.splice(idx, 1)
}

function duplicateRow(idx) {
  const src = rows.value[idx]
  const newRow = { ...src, _id: ++rowIdCounter, _errors: null }
  rows.value.splice(idx + 1, 0, newRow)
}

function addColumn(key) {
  if (!selectedFields.value.includes(key)) {
    selectedFields.value.push(key)
    rows.value.forEach(row => { if (!(key in row)) row[key] = '' })
  }
  showAddColumnDialog.value = false
}

function removeColumn(key) {
  const field = allFields.find(f => f.key === key)
  if (field && (field.required || field.autoGenerate)) return
  const idx = selectedFields.value.indexOf(key)
  if (idx >= 0) selectedFields.value.splice(idx, 1)
}

// ─── Step 3: Validation ───
const validating = ref(false)
const validationResult = ref(null)

const productCount = computed(() => {
  const titles = new Set(rows.value.map(r => r['Title']).filter(Boolean))
  return titles.size || (rows.value.length > 0 ? 1 : 0)
})

async function validateData() {
  validating.value = true
  validationResult.value = null

  const errors = []
  const skus = new Set()

  rows.value.forEach((row, idx) => {
    row._errors = {}
    // Auto-generate Handle from Title
    row['Handle'] = generateHandle(row['Title'])

    // Title required
    if (selectedFields.value.includes('Title') && (!row['Title'] || !row['Title'].trim())) {
      errors.push({ row: idx + 1, field: 'Title', message: locale.value === 'zh' ? '商品标题不能为空' : 'Title is required' })
      row._errors['Title'] = locale.value === 'zh' ? '必填' : 'Required'
    }

    // SKU required and unique
    if (selectedFields.value.includes('Variant SKU')) {
      if (!row['Variant SKU'] || !row['Variant SKU'].trim()) {
        errors.push({ row: idx + 1, field: 'Variant SKU', message: locale.value === 'zh' ? 'SKU 不能为空' : 'SKU is required' })
        row._errors['Variant SKU'] = locale.value === 'zh' ? '必填' : 'Required'
      } else if (skus.has(row['Variant SKU'].trim())) {
        errors.push({ row: idx + 1, field: 'Variant SKU', message: `SKU "${row['Variant SKU']}" ${locale.value === 'zh' ? '重复' : 'duplicated'}` })
        row._errors['Variant SKU'] = locale.value === 'zh' ? 'SKU 重复' : 'Duplicated'
      } else {
        skus.add(row['Variant SKU'].trim())
      }
    }

    // Price must be number
    if (selectedFields.value.includes('Variant Price') && row['Variant Price']) {
      if (isNaN(Number(row['Variant Price']))) {
        errors.push({ row: idx + 1, field: 'Variant Price', message: locale.value === 'zh' ? '价格必须为数字' : 'Must be a number' })
        row._errors['Variant Price'] = locale.value === 'zh' ? '必须为数字' : 'Must be number'
      }
    }

    // Compare at price
    if (row['Variant Compare At Price'] && isNaN(Number(row['Variant Compare At Price']))) {
      errors.push({ row: idx + 1, field: 'Variant Compare At Price', message: locale.value === 'zh' ? '对比价格必须为数字' : 'Must be a number' })
      row._errors['Variant Compare At Price'] = locale.value === 'zh' ? '必须为数字' : 'Must be number'
    }

    // Grams
    if (row['Variant Grams'] && isNaN(Number(row['Variant Grams']))) {
      errors.push({ row: idx + 1, field: 'Variant Grams', message: locale.value === 'zh' ? '重量必须为数字' : 'Must be a number' })
      row._errors['Variant Grams'] = locale.value === 'zh' ? '必须为数字' : 'Must be number'
    }
  })

  await new Promise(r => setTimeout(r, 600))

  if (errors.length > 0) {
    validationResult.value = { valid: false, errors }
  } else {
    const msg = locale.value === 'zh'
      ? `${productCount.value} 个商品、${rows.value.length} 个变体数据验证通过。`
      : `${productCount.value} product(s), ${rows.value.length} variant(s) validated.`
    validationResult.value = { valid: true, message: msg }
  }

  validating.value = false
}

// ─── Step 4: Export / Upload ───
const uploading = ref(false)
const uploadProgress = ref(0)
const uploadResult = ref(null)

function exportCSV() {
  // Auto-fill Handle from Title
  rows.value.forEach(row => {
    row['Handle'] = generateHandle(row['Title'])
  })

  const allCsvHeaders = allFields.map(f => f.key)
  const headerLine = allCsvHeaders.join(',')

  const csvRows = rows.value.map(row => {
    return allCsvHeaders.map(key => {
      const val = row[key] || ''
      if (val.includes(',') || val.includes('"') || val.includes('\n')) {
        return `"${val.replace(/"/g, '""')}"`
      }
      return val
    }).join(',')
  })

  const csv = [headerLine, ...csvRows].join('\n')
  const blob = new Blob(['\ufeff' + csv], { type: 'text/csv;charset=utf-8;' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `shopify_products_${new Date().toISOString().slice(0, 10)}.csv`
  a.click()
  URL.revokeObjectURL(url)
}

async function uploadToShopify() {
  if (uploading.value) return
  uploading.value = true
  uploadProgress.value = 0
  uploadResult.value = null

  // Auto-fill Handle from Title
  rows.value.forEach(row => {
    row['Handle'] = generateHandle(row['Title'])
  })

  // Group rows by Title into products
  const productMap = {}
  rows.value.forEach(row => {
    const title = row['Title'] || 'Untitled'
    if (!productMap[title]) {
      productMap[title] = {
        title,
        handle: generateHandle(title),
        body_html: row['Body (HTML)'] || '',
        vendor: row['Vendor'] || '',
        product_type: row['Type'] || '',
        tags: row['Tags'] || '',
        status: row['Status'] || 'draft',
        option1_name: row['Option1 Name'] || undefined,
        option2_name: row['Option2 Name'] || undefined,
        option3_name: row['Option3 Name'] || undefined,
        variants: [],
        images: [],
      }
    }
    productMap[title].variants.push({
      option1: row['Option1 Value'] || 'Default Title',
      option2: row['Option2 Value'] || undefined,
      option3: row['Option3 Value'] || undefined,
      sku: row['Variant SKU'] || '',
      barcode: row['Variant Barcode'] || '',
      price: row['Variant Price'] || '0.00',
      compare_at_price: row['Variant Compare At Price'] || undefined,
      grams: row['Variant Grams'] || undefined,
      weight_unit: row['Variant Weight Unit'] || 'g',
      inventory_management: row['Variant Inventory Tracker'] || 'shopify',
      inventory_policy: row['Variant Inventory Policy'] || 'deny',
      fulfillment_service: row['Variant Fulfillment Service'] || 'manual',
      requires_shipping: row['Variant Requires Shipping'] !== 'false',
      taxable: row['Variant Taxable'] !== 'false',
      cost: row['Cost per item'] || undefined,
    })
    if (row['Image Src']) {
      productMap[title].images.push({
        src: row['Image Src'],
        alt: row['Image Alt Text'] || '',
        position: row['Image Position'] ? Number(row['Image Position']) : undefined,
      })
    }
  })

  const products = Object.values(productMap)

  const progressInterval = setInterval(() => {
    if (uploadProgress.value < 90) uploadProgress.value += 10
  }, 500)

  try {
    const res = await api.post('/new-product/create', { products })
    uploadResult.value = res.data
    uploadProgress.value = 100
  } catch (err) {
    uploadResult.value = {
      data: [{ title: locale.value === 'zh' ? '上传失败' : 'Upload failed', status: 'error', message: err.response?.data?.message || err.message }],
      summary: { created: 0, failed: products.length, total: products.length },
    }
    uploadProgress.value = 100
  } finally {
    clearInterval(progressInterval)
    uploading.value = false
  }
}

// ─── Navigation ───
function goToStep(step) {
  if (step === 1 && rows.value.length === 0) {
    addRow()
  }
  if (step === 2) {
    validateData()
  }
  currentStep.value = step
}
</script>

<style scoped>
.new-product-entry {
  max-width: 1200px;
  margin: 0 auto;
  padding: 0 16px;
}

/* Header */
.entry-header {
  display: flex;
  align-items: center;
  gap: 16px;
  margin-bottom: 24px;
}
.back-btn {
  display: flex;
  align-items: center;
  gap: 4px;
  padding: 6px 12px;
  border: 1px solid #e5e7eb;
  border-radius: 6px;
  background: white;
  color: #6b7280;
  cursor: pointer;
  font-size: 13px;
  transition: all 0.2s;
}
.back-btn:hover { border-color: #9333ea; color: #9333ea; }
.entry-title { font-size: 22px; font-weight: 700; color: #1f2937; }

/* Stepper */
.stepper {
  display: flex;
  align-items: center;
  margin-bottom: 32px;
  padding: 16px 24px;
  background: #f9fafb;
  border-radius: 12px;
}
.step {
  display: flex;
  align-items: center;
  gap: 8px;
  flex: 1;
}
.step-circle {
  width: 28px;
  height: 28px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 12px;
  font-weight: 700;
  background: #e5e7eb;
  color: #9ca3af;
  transition: all 0.3s;
  flex-shrink: 0;
}
.step.active .step-circle { background: #9333ea; color: white; }
.step.done .step-circle { background: #10b981; color: white; }
.step-label { font-size: 13px; color: #6b7280; white-space: nowrap; transition: all 0.3s; }
.step.active .step-label { color: #9333ea; font-weight: 600; }
.step.done .step-label { color: #10b981; }
.step-line {
  flex: 1;
  height: 2px;
  background: #e5e7eb;
  margin: 0 12px;
  transition: all 0.3s;
}
.step-line.filled { background: #10b981; }

/* Step Content */
.step-content { animation: slideIn 0.3s ease; }
.step-desc { margin-bottom: 20px; }
.step-desc h3 { font-size: 18px; font-weight: 600; color: #1f2937; margin-bottom: 4px; }
.step-desc p { font-size: 14px; color: #6b7280; }

/* Field Selection */
.field-categories { display: flex; flex-direction: column; gap: 20px; }
.cat-title { font-size: 14px; font-weight: 600; color: #374151; margin-bottom: 8px; }
.field-chips { display: flex; flex-wrap: wrap; gap: 8px; }
.field-chip {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 6px 12px;
  border: 1px solid #e5e7eb;
  border-radius: 20px;
  font-size: 13px;
  cursor: pointer;
  transition: all 0.2s;
  user-select: none;
}
.field-chip:hover { border-color: #9333ea; }
.field-chip.selected { background: #f3e8ff; border-color: #9333ea; color: #7c3aed; }
.field-chip.required { background: #fef3c7; border-color: #f59e0b; }
.field-chip.disabled { cursor: not-allowed; opacity: 0.8; }
.field-chip input { display: none; }
.chip-badge { font-size: 10px; background: #f59e0b; color: white; padding: 1px 5px; border-radius: 8px; }
.chip-auto { background: #6366f1; }

/* Table */
.table-toolbar {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-bottom: 12px;
}
.row-count { font-size: 13px; color: #9ca3af; margin-left: auto; }
.table-wrapper {
  overflow-x: auto;
  border: 1px solid #e5e7eb;
  border-radius: 8px;
  margin-bottom: 20px;
}
.data-table {
  width: 100%;
  border-collapse: collapse;
  font-size: 13px;
}
.data-table th, .data-table td {
  padding: 8px 10px;
  border-bottom: 1px solid #f3f4f6;
  text-align: left;
  white-space: nowrap;
}
.data-table th {
  background: #f9fafb;
  font-weight: 600;
  color: #374151;
  position: sticky;
  top: 0;
  z-index: 1;
}
.col-header { position: relative; }
.handle-hint {
  display: block;
  font-size: 10px;
  color: #9ca3af;
  font-weight: 400;
  font-style: italic;
}
.col-remove {
  position: absolute;
  top: 2px;
  right: 2px;
  width: 16px;
  height: 16px;
  border: none;
  background: #ef4444;
  color: white;
  border-radius: 50%;
  font-size: 11px;
  cursor: pointer;
  display: none;
  align-items: center;
  justify-content: center;
  line-height: 1;
}
.col-header:hover .col-remove { display: flex; }
.row-num { width: 36px; text-align: center; color: #9ca3af; }
.row-actions { width: 70px; text-align: center; }
.cell { min-width: 120px; position: relative; }
.cell-error { background: #fef2f2; }
.cell-input {
  width: 100%;
  padding: 4px 8px;
  border: 1px solid #e5e7eb;
  border-radius: 4px;
  font-size: 13px;
  transition: border-color 0.2s;
}
.cell-input:focus { border-color: #9333ea; outline: none; }
.cell-readonly { background: #f9fafb; color: #6b7280; cursor: not-allowed; }
.cell-textarea { resize: vertical; min-height: 40px; }
.cell-error-tip {
  position: absolute;
  bottom: -14px;
  left: 10px;
  font-size: 10px;
  color: #ef4444;
}

/* Buttons */
.btn-primary {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  padding: 10px 20px;
  background: #9333ea;
  color: white;
  border: none;
  border-radius: 8px;
  font-size: 14px;
  font-weight: 600;
  cursor: pointer;
  transition: all 0.2s;
}
.btn-primary:hover { background: #7c3aed; }
.btn-primary:disabled { opacity: 0.5; cursor: not-allowed; }
.btn-secondary {
  padding: 10px 20px;
  background: white;
  color: #374151;
  border: 1px solid #e5e7eb;
  border-radius: 8px;
  font-size: 14px;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.2s;
}
.btn-secondary:hover { border-color: #9333ea; color: #9333ea; }
.btn-outline {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  padding: 6px 12px;
  background: white;
  color: #6b7280;
  border: 1px solid #e5e7eb;
  border-radius: 6px;
  font-size: 13px;
  cursor: pointer;
  transition: all 0.2s;
}
.btn-outline:hover { border-color: #9333ea; color: #9333ea; }
.btn-sm { padding: 5px 10px; font-size: 12px; }
.btn-icon {
  width: 28px;
  height: 28px;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  border: none;
  background: transparent;
  border-radius: 4px;
  cursor: pointer;
  color: #6b7280;
  transition: all 0.2s;
}
.btn-icon:hover { background: #f3f4f6; }
.btn-icon.btn-danger:hover { background: #fef2f2; color: #ef4444; }
.step-actions { display: flex; gap: 12px; justify-content: flex-end; margin-top: 24px; }

/* Validation */
.validate-loading { display: flex; align-items: center; gap: 12px; padding: 40px; justify-content: center; }
.spinner {
  width: 24px; height: 24px;
  border: 3px solid #e5e7eb;
  border-top-color: #9333ea;
  border-radius: 50%;
  animation: spin 0.8s linear infinite;
}
@keyframes spin { to { transform: rotate(360deg); } }
.validate-result { text-align: center; padding: 40px 20px; }
.validate-success h4 { color: #10b981; font-size: 18px; margin: 12px 0 8px; }
.validate-success p { color: #6b7280; }
.validate-summary { margin-top: 12px; display: flex; gap: 20px; justify-content: center; font-size: 14px; color: #374151; }
.validate-errors h4 { color: #ef4444; font-size: 18px; margin: 12px 0 8px; }
.validate-errors p { color: #6b7280; margin-bottom: 12px; }
.error-list { text-align: left; max-width: 500px; margin: 0 auto; list-style: none; padding: 0; }
.error-list li { padding: 6px 0; border-bottom: 1px solid #fef2f2; font-size: 13px; color: #374151; }

/* Export */
.export-options { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 24px; }
.export-card {
  padding: 32px 24px;
  border: 2px solid #e5e7eb;
  border-radius: 12px;
  text-align: center;
  cursor: pointer;
  transition: all 0.3s;
}
.export-card:hover { border-color: #9333ea; transform: translateY(-2px); box-shadow: 0 4px 12px rgba(147, 51, 234, 0.1); }
.export-card.uploading { pointer-events: none; opacity: 0.7; }
.export-icon { margin-bottom: 12px; }
.export-card h4 { font-size: 16px; font-weight: 600; color: #1f2937; margin-bottom: 8px; }
.export-card p { font-size: 13px; color: #6b7280; }
.upload-progress { margin-top: 12px; display: flex; align-items: center; gap: 8px; }
.progress-bar { flex: 1; height: 6px; background: #e5e7eb; border-radius: 3px; overflow: hidden; }
.progress-fill { height: 100%; background: #10b981; transition: width 0.3s; border-radius: 3px; }

/* Upload Result */
.upload-result { margin-bottom: 20px; }
.result-summary { padding: 12px 16px; border-radius: 8px; font-size: 14px; display: flex; gap: 16px; }
.result-summary.success { background: #ecfdf5; color: #065f46; }
.result-summary.partial { background: #fef3c7; color: #92400e; }
.result-item { padding: 8px 16px; border-bottom: 1px solid #f3f4f6; display: flex; justify-content: space-between; font-size: 13px; }
.result-item.created .result-status { color: #10b981; }
.result-item.error .result-status { color: #ef4444; }

/* Dialog */
.dialog-overlay {
  position: fixed;
  inset: 0;
  background: rgba(0, 0, 0, 0.4);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 1000;
}
.dialog-box {
  background: white;
  border-radius: 12px;
  padding: 24px;
  max-width: 500px;
  width: 90%;
  max-height: 70vh;
  overflow-y: auto;
}
.dialog-box h3 { font-size: 18px; font-weight: 600; margin-bottom: 8px; }
.dialog-box p { font-size: 14px; color: #6b7280; margin-bottom: 16px; }
.dialog-fields { display: flex; flex-direction: column; gap: 4px; }
.dialog-field-item {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 8px 12px;
  border-radius: 6px;
  cursor: pointer;
  transition: background 0.2s;
  font-size: 13px;
}
.dialog-field-item:hover { background: #f3e8ff; }
.field-cat-tag { font-size: 11px; color: #9ca3af; background: #f3f4f6; padding: 2px 6px; border-radius: 4px; }
.dialog-actions { margin-top: 16px; display: flex; justify-content: flex-end; }

/* Transitions */
.slide-fade-enter-active { transition: all 0.3s ease; }
.slide-fade-leave-active { transition: all 0.2s ease; }
.slide-fade-enter-from { transform: translateX(20px); opacity: 0; }
.slide-fade-leave-to { transform: translateX(-20px); opacity: 0; }
.fade-enter-active, .fade-leave-active { transition: opacity 0.2s; }
.fade-enter-from, .fade-leave-to { opacity: 0; }
.row-fade-enter-active { transition: all 0.3s ease; }
.row-fade-leave-active { transition: all 0.2s ease; }
.row-fade-enter-from { opacity: 0; transform: translateY(-10px); }
.row-fade-leave-to { opacity: 0; transform: translateX(20px); }
@keyframes slideIn { from { opacity: 0; transform: translateY(10px); } to { opacity: 1; transform: translateY(0); } }
</style>
