services:
  backend:
    build: ./backend
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - /data/exhibition-app/database:/data/exhibition-app/database
      - /home/ubuntu/Exhibition-Manager/frontend/dist:/frontend/dist:ro
    ports:
      - '127.0.0.1:3001:3001'
